// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RabbitMQRead.AppContext;

#nullable disable

namespace EntityLayer.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240124042826_create10000")]
    partial class create10000
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RabbitMQRead.Entity.CallInformation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("External")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Internal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SipStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("CallInformations");
                });

            modelBuilder.Entity("RabbitMQRead.Entity.CallInformationDetailed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CallAnswered")
                        .HasColumnType("text");

                    b.Property<int?>("CallDuraction")
                        .HasColumnType("integer");

                    b.Property<string>("CallEnded")
                        .HasColumnType("text");

                    b.Property<string>("CallId")
                        .HasColumnType("text");

                    b.Property<string>("CallStarted")
                        .HasColumnType("text");

                    b.Property<int>("CallType")
                        .HasColumnType("integer");

                    b.Property<string>("Chain")
                        .HasColumnType("text");

                    b.Property<string>("Cif")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DialResult")
                        .HasColumnType("integer");

                    b.Property<string>("External")
                        .HasColumnType("text");

                    b.Property<string>("GatewayName")
                        .HasColumnType("text");

                    b.Property<string>("Internal")
                        .HasColumnType("text");

                    b.Property<string>("IsMakeCall")
                        .HasColumnType("text");

                    b.Property<string>("ReasonChanged")
                        .HasColumnType("text");

                    b.Property<string>("ReasonTerminated")
                        .HasColumnType("text");

                    b.Property<string>("SipStatus")
                        .HasColumnType("text");

                    b.Property<string>("SipStatusRecived")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CallInformationDetaileds");
                });
#pragma warning restore 612, 618
        }
    }
}
